#!/usr/bin/bash

PUBURL="http://files.michiwend.com/share"
SSHURL="michael@michiwend.com:files/share"


USAGE="\nBenutzung:\nbash-share Quelldatei [Zieldatei]\n"

if [[ $# -gt 0 && $#  -lt 3 ]]; then

  if [ -f $1 ]; then

    scp $1 $SSHURL/$2 2> /dev/null

    if [ $? == 0 ]; then
      
      if [ $# == 2 ]; then
        URL="$PUBURL/$2"
      else
        URL="$PUBURL/$(basename $1)"
      fi

      # Aufruf für normale Zwischenablage (Strg + V)
      echo $URL | xclip -selection clipboard
      # Aufruf für mittlere Maustaste
      #echo $URL | xclip 
      echo "$URL wurde in dei Zwischenablage kopiert."

    else
      echo "Übertragung fehlgeschlagen"
    fi

  else
    echo "'$1' ist keine gültige Datei"
  fi

else
  echo -e $USAGE
fi
